### ISSUE TITLE
It's always red :(

### ISSUE THREAD

**Issue by Aghits** [GabrieleMaurina/chess-cheat#1]
also i got this error is it normal?  `Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 804, in callit
    func(*args)
  File "C:\Users\MSI\Desktop\chess-cheat-master\src\chess-cheat.py", line 216, in cheat
    move = run_fish(s, fen)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\timeout_decorator\timeout_decorator.py", line 91, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\site-packages\timeout_decorator\timeout_decorator.py", line 146, in __call__
    self.__process.start()
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x00000261492D1A60>: it's not the same object as __main__.run_fish
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input`

**Comment by GabrieleMaurina** [comment]
Hello,
sorry for the late reply. For some reason I didn't get the email.

Off the top of my head I don't know what is causing the problem you are reporting. Are you still experiencing it? Or have you managed to fix it in the meantime?

**Comment by w0dm4n** [comment]
Hello, i'm experience the same issue while testing with stockfish 12/11/10 python 3.8
Stockfish globally or with specified path:

```
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 804, in callit
    func(*args)
  File "chess-cheat.py", line 220, in cheat
    move = run_fish(s, fen)
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\site-packages\timeout_decorator\timeout_decorator.py", line 92, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\site-packages\timeout_decorator\timeout_decorator.py", line 147, in __call__
    self.__process.start()
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x0000023D5B6A85E0>: it's not the same object as __main__.run_fish
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\X\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by w0dm4n** [comment]
Just found the issue, it's the timeout decorator from the fnc run_fish that create -> https://stackoverflow.com/questions/49936735/a-timeout-decorator-class-with-multiprocessing-gives-a-pickling-error

3 fucking hour of struggling eheh

**Comment by slarkb** [comment]
> Just found the issue, it's the timeout decorator from the fnc run_fish that create -> https://stackoverflow.com/questions/49936735/a-timeout-decorator-class-with-multiprocessing-gives-a-pickling-error
> 
> 3 fucking hour of struggling eheh

what do you do to fix it

**Comment by w0dm4n** [comment]
the issue is due to the fact that you start stockfish through another process when you're setting his direct path, so when it tries to make a fork for the max timeout it cant relate to the child process, so you gotta set it globally loaded otherwise or change the `run_fish` for a different behavior (like loading directly stockfish into that child)

**Comment by w0dm4n** [comment]
also, the bot run only smoothly on same resolution then expected on: https://github.com/Elucidation/tensorflow_chessbot

**Comment by GabrieleMaurina** [comment]
> the issue is due to the fact that you start stockfish through another process when you're setting his direct path, so when it tries to make a fork for the max timeout it cant relate to the child process, so you gotta set it globally loaded otherwise or change the `run_fish` for a different behavior (like loading directly stockfish into that child)

Is this something that happens only when setting the path of stockfish?

**Comment by GabrieleMaurina** [comment]
> also, the bot run only smoothly on same resolution then expected on: https://github.com/Elucidation/tensorflow_chessbot

You can use the "Board" buttton in the GUI to tell chess-cheat where and how big the board is. You don't need to be precise to the pixel, but this helps greatly to recognize the board.

Once the board is found, the resolution doesn't matter because it is scaled to the resolution needed by the ANN.

**Comment by w0dm4n** [comment]
Weird cause i had less issues using the same one.

> Is this something that happens only when setting the path of stockfish?
didn't tried globally cause it wasn't detecting my stockfish version, a real pain in the ass to setup

**Comment by SSummer-UI** [comment]
I'm having the same issue with @Aghits @w0dm4n and I'm not as familiar with python as him. Is there an simple "change the code" solution to this issue?

**Comment by w0dm4n** [comment]
So you're basically asking for a 'please copy paste your solution'?... sorry then i suggest you to learn python 😄

**Comment by SSummer-UI** [comment]
A quick pr to this issue: https://github.com/GabrieleMaurina/chess-cheat/pull/3/commits

**Comment by Nur47-blip** [comment]
> A quick pr to this issue: https://github.com/GabrieleMaurina/chess-cheat/pull/3/commits

My GUI freeze after some time, do you know how to fix it?
![image](https://user-images.githubusercontent.com/67987788/110200495-e78b7980-7e90-11eb-86d7-f49eff639f0f.png)

**Comment by walhackmaster** [comment]
> A quick pr to this issue: https://github.com/GabrieleMaurina/chess-cheat/pull/3/commits

still same error on me
