### ISSUE TITLE
AttributeError: 'Stockfish' object has no attribute '_stockfish'

### ISSUE THREAD

**Issue by Fishexee** [GabrieleMaurina/chess-cheat#11]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\Lib\site-packages\chess-cheat.py", line 249, in <module>
    main()
  File "F:\Lib\site-packages\chess-cheat.py", line 241, in main
    s = create_fish()
        ^^^^^^^^^^^^^
  File "F:\Lib\site-packages\chess-cheat.py", line 235, in create_fish
    s = Stockfish()#parameters={'Threads':cpu_count()})
        ^^^^^^^^^^^
  File "F:\Lib\site-packages\stockfish\models.py", line 47, in __init__
    self._stockfish = subprocess.Popen(
                      ^^^^^^^^^^^^^^^^^
  File "F:\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function Stockfish.__del__ at 0x0000022FBF2B3880>
Traceback (most recent call last):
  File "F:\Lib\site-packages\stockfish\models.py", line 757, in __del__
    if self._stockfish.poll() is None:
       ^^^^^^^^^^^^^^^
AttributeError: 'Stockfish' object has no attribute '_stockfish'

**Comment by benfodil** [comment]
same problems , i use python v3.11 btw

**Comment by benfodil** [comment]
> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "F:\Lib\site-packages\chess-cheat.py", line 249, in main() File "F:\Lib\site-packages\chess-cheat.py", line 241, in main s = create_fish() ^^^^^^^^^^^^^ File "F:\Lib\site-packages\chess-cheat.py", line 235, in create_fish s = Stockfish()#parameters={'Threads':cpu_count()}) ^^^^^^^^^^^ File "F:\Lib\site-packages\stockfish\models.py", line 47, in **init** self._stockfish = subprocess.Popen( ^^^^^^^^^^^^^^^^^ File "F:\Lib\subprocess.py", line 1024, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "F:\Lib\subprocess.py", line 1493, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [WinError 2] The system cannot find the file specified Exception ignored in: <function Stockfish.**del** at 0x0000022FBF2B3880> Traceback (most recent call last): File "F:\Lib\site-packages\stockfish\models.py", line 757, in **del** if self._stockfish.poll() is None: ^^^^^^^^^^^^^^^ AttributeError: 'Stockfish' object has no attribute '_stockfish'

same problems , i use python v3.11 btw
