### ISSUE TITLE
Error with stockfish

### ISSUE THREAD

**Issue by etfriedman** [GabrieleMaurina/chess-cheat#2]
I'm getting this error:
`(py38) C:\Users\etfri>python -m chess-cheat
Traceback (most recent call last):
  File "C:\Users\etfri\anaconda3\envs\py38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\etfri\anaconda3\envs\py38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\etfri\anaconda3\envs\py38\lib\site-packages\chess-cheat.py", line 249, in <module>
    main()
  File "C:\Users\etfri\anaconda3\envs\py38\lib\site-packages\chess-cheat.py", line 241, in main
    s = create_fish()
  File "C:\Users\etfri\anaconda3\envs\py38\lib\site-packages\chess-cheat.py", line 235, in create_fish
    s = Stockfish()#parameters={'Threads':cpu_count()})
  File "C:\Users\etfri\anaconda3\envs\py38\lib\site-packages\stockfish\models.py", line 33, in __init__
    self.stockfish = subprocess.Popen(
  File "C:\Users\etfri\anaconda3\envs\py38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\etfri\anaconda3\envs\py38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function Stockfish.__del__ at 0x0000029D38C0FDC0>
Traceback (most recent call last):
  File "C:\Users\etfri\anaconda3\envs\py38\lib\site-packages\stockfish\models.py", line 270, in __del__
    self.stockfish.kill()
AttributeError: 'Stockfish' object has no attribute 'stockfish'`

I have installed the stockfish binaries to C:\Users\etfri\Desktop\stockfishlib,

but where should I include the stockfish = Stockfish("/Users/etfri/Desktop/stockfishlib")? inside the Stockfish class, before / after?

**Comment by GabrieleMaurina** [comment]
Hello,
sorry for the late reply.

The code assumes that stockfish is installed globally, so it is initialized without passing any path to it. Like so:
```python
stockfish = Stockfish()
```

If you want to manually change the code to include your path, you have to go into src/chess-cheat.py and change this function:
```python
def create_fish():  
    s = Stockfish()#parameters={'Threads':cpu_count()})
    s.set_depth(20)
    #print(s.get_parameters())
    return s
```
You can specify the path in the Stockfish constructor.

**Comment by SSummer-UI** [comment]
Alternatively, you can just add an stockfish.exe into system32 file in C:\Windows\System32\ as it is natively a global path variable.
