### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by walhackmaster** [GabrieleMaurina/chess-cheat#6]
how to fix this error :
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\Program Files (x86)\Python\Python38\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "D:\Program Files (x86)\Python\Python38\lib\site-packages\chess-cheat.py", line 220, in cheat
    move = run_fish(s, fen)
  File "D:\Program Files (x86)\Python\Python38\lib\site-packages\timeout_decorator\timeout_decorator.py", line 92, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "D:\Program Files (x86)\Python\Python38\lib\site-packages\timeout_decorator\timeout_decorator.py", line 147, in __call__
    self.__process.start()
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x000001FC816BB160>: it's not the same object as __main__.run_fish
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files (x86)\Python\Python38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by JFGTX** [comment]
Same thing :/ 

Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Python\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "D:\Python\lib\site-packages\chess-cheat.py", line 220, in cheat
    move = run_fish(s, fen)
  File "D:\Python\lib\site-packages\timeout_decorator\timeout_decorator.py", line 92, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "D:\Python\lib\site-packages\timeout_decorator\timeout_decorator.py", line 147, in __call__
    self.__process.start()
  File "D:\Python\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Python\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Python\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "D:\Python\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Python\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x0000015C639EFD70>: it's not the same object as __main__.run_fish
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Python\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by divakarmal** [comment]
same

**Comment by Pau1Net** [comment]
> same

The error is in "@lru_cache". The code was written by poor fellow, apparently, on Linux, so give up the idea of trying to "reanimate" him. I fixed all these errors, it even started and even found the board, but due to the developer's crookedness, whenever there is some problem (any), the program creates a new engine process. I got to 11. My computer on i9 got pretty bad. I decided that, too. But then he just stopped responding. Immediately after starting the program stops responding. Yes, I admit that the dev done a lot of work, but the program has clearly been tested little (if at all tested more than once). After spending more than 3 days behind this application, I give up. Although the idea is interesting. I will try to write a similar one 
but already with a reference to Windows
