### ISSUE TITLE
AttributeError: 'Stockfish' object has no attribute 'stockfish'

### ISSUE THREAD

**Issue by cy-bug** [GabrieleMaurina/chess-cheat#7]
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\lib\site-packages\chess-cheat.py", line 249, in <module>
    main()
  File "C:\Python39\lib\site-packages\chess-cheat.py", line 241, in main
    s = create_fish()
  File "C:\Python39\lib\site-packages\chess-cheat.py", line 235, in create_fish
    s = Stockfish()#parameters={'Threads':cpu_count()})
  File "C:\Python39\lib\site-packages\stockfish\models.py", line 35, in __init__
    self.stockfish = subprocess.Popen(
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function Stockfish.__del__ at 0x00000224EDB56C10>
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\stockfish\models.py", line 396, in __del__
    self._put("quit")
  File "C:\Python39\lib\site-packages\stockfish\models.py", line 80, in _put
    if not self.stockfish.stdin:
AttributeError: 'Stockfish' object has no attribute 'stockfish'

### I use python 3.9

**Comment by RaphOfficial** [comment]
Same issue

**Comment by MeblIkea** [comment]
Same issue, but for me it's more like `AttributeError: 'Stockfish' object has no attribute '_stockfish'`, and i tried it on Windows (10) & Linux (Garuda Linux), and same issue :/

**Comment by hp2309** [comment]
This happens because you haven't specified the path to the stockfish engine. Download stockfish from https://stockfishchess.org/download/ and pass the path to stockfish... .exe in the file chess-cheat.py in the "create_fish()" function like so.
OLD: 
```
def create_fish():	
	s = Stockfish()#parameters={'Threads':cpu_count()})
	s.set_depth(20)
	#print(s.get_parameters())
	return s

```
NEW:
```
def create_fish():	
	s = Stockfish('stockfish_15_win_x64_avx2\stockfish_15_x64_avx2.exe')#parameters={'Threads':cpu_count()})
	s.set_depth(20)
	#print(s.get_parameters())
	return s
```

**Comment by Pau1Net** [comment]
> 

Could you describe in more detail exactly how you set the path? I've already tried everything. And "pathlib" and "os", nothing helps, the error persists.

**Comment by Pau1Net** [comment]
Anyway, I'm currently doing a complete code correction. It is clearly written on Linux.

**Comment by Filipposcmd** [comment]
> This happens because you haven't specified the path to the stockfish engine. Download stockfish from https://stockfishchess.org/download/ and pass the path to stockfish... .exe in the file chess-cheat.py in the "create_fish()" function like so. OLD:
> 
> ```
> def create_fish():	
> 	s = Stockfish()#parameters={'Threads':cpu_count()})
> 	s.set_depth(20)
> 	#print(s.get_parameters())
> 	return s
> ```
> 
> NEW:
> 
> ```
> def create_fish():	
> 	s = Stockfish('stockfish_15_win_x64_avx2\stockfish_15_x64_avx2.exe')#parameters={'Threads':cpu_count()})
> 	s.set_depth(20)
> 	#print(s.get_parameters())
> 	return s
> ```

still..... It isn't working for me
